### ISSUE TITLE
What's the relationship of this code to the CPython standard library?

### ISSUE THREAD

**Issue by gvanrossum** [mythonlang/pgen2#1]
There's a package named pgen2 in the standard library: https://github.com/python/cpython/tree/master/Lib/lib2to3/pgen2. I wrote that between 2003-2005.

How does the code here relate to that? You don't seem to have a license.

**Comment by jriehl** [comment]
Hi Guido,

I hadn't seen your Python implementation as it was hiding in lib2to3.  I wrote this independently for the Basil project, and I can't recall if this made it into PyPy or not (that would have been around 2003, IIRC).  My code is a direct Python port of your C code, and I wrote it after PEP-269 didn't get any community uptake (only you and I seemed interested in 269, and grad school distracted me from fixing the segfault problem in the reference implementation).  As far as I'm concerned, this code is BSD licensed. Sorry that I neglected to make that clear.

So.  What shall we do about this apparent co-invention?  If I can port Mython to leverage your implementation, I can shut this down.  I'd prefer to see your implementation moved out of lib2to3 and documented as a first class member of the standard library.

Thanks,
-Jon

**Comment by gvanrossum** [comment]
Thanks for replying. Given the lack of interest in PEP 269 (which I had forgotten about -- sorry!) I don't think there's anything to do -- maybe you can add an explicit BSD license and a comment explaining you invented this independently.

I don't feel like pushing for a refactoring of lib2to3/pgen2 in the stdlib right now, there are various issues (e.g. lib2to3/pgen2/tokenize.py is slightly different from the toplevel tokenize.py, and there are good reasons for that, since it must be able to parse Python 2!

Personally I am more interested in pursuing a totally different parser technology based on PEG and packrat, but it's too soon to talk about it.

Feel free to close this issue.

**Comment by jriehl** [comment]
Oh dear.  I'll have to be careful to avoid co-invention here as well.  I developed a PEG packrat parser at Continuum Analytics in 2015 to demonstrate using Numba for parsing, and I'd like them to open source it (how about it @pzwang?).

**Comment by gvanrossum** [comment]
As long as you're not going for a patent you should be fine, right? :-)

**Comment by pzwang** [comment]
I don't see why not - but I'll defer to @seibert on this.
